version: '2'
services:
   eurekaserver:
      image: 'seanimus/eureka:v1'
      ports:
         - '8761:8761'
      networks:
         - 'spring-cloud-network'
   configserver:
      image: 'seanimus/configserver:v1'
      ports:
         - '8888:8888'
      networks:
         - 'spring-cloud-network'
      environment:
         ENCRYPT_KEY: 'DEVELOP'
         EUREKASERVER_URI: 'http://eurekaserver:8761/eureka/'
         EUREKASERVER_PORT: '8761'
      depends_on:
         - 'eurekaserver'
   blogservice:
      image: 'seanimus/blog-crud:v1'
      ports:
         - '8080:8080'
      networks:
         - 'spring-cloud-network'
      environment:
         PROFILE: 'default'
         SERVER_PORT: '8080'
         ENCRYPT_KEY: 'DEVELOP'
         CONFIGSERVER_URI: 'http://configserver:8888'
         CONFIGSERVER_PORT: '8888'
         EUREKASERVER_URI: 'http://eurekaserver:8761/eureka/'
         EUREKASERVER_PORT: '8761'
      links:
         - 'configserver:configserver'
      depends_on:
         - 'configserver'
         - 'eurekaserver'
   userservice:
      image: 'seanimus/userservice:v1'
      ports:
         - '8081:8081'
      networks:
         - 'spring-cloud-network'
      environment:
         PROFILE: 'default'
         SERVER_PORT: '8081'
         ENCRYPT_KEY: 'DEVELOP'
         CONFIGSERVER_URI: 'http://configserver:8888'
         CONFIGSERVER_PORT: '8888'
         EUREKASERVER_URI: 'http://eurekaserver:8761/eureka/'
         EUREKASERVER_PORT: '8761'
      links:
         - 'configserver:configserver'
      depends_on:
         - 'configserver'
         - 'eurekaserver'
   zuulservice:
      image: 'seanimus/zuul:v1'
      ports:
         - '5555:5555'
      networks:
         - 'spring-cloud-network'
      environment:
         PROFILE: 'default'
         SERVER_PORT: '8081'
         ENCRYPT_KEY: 'DEVELOP'
         CONFIGSERVER_URI: 'http://configserver:8888'
         CONFIGSERVER_PORT: '8888'
         EUREKASERVER_URI: 'http://eurekaserver:8761/eureka/'
         EUREKASERVER_PORT: '8761'
      links:
         - 'configserver:configserver'
      depends_on:
         - 'configserver'
         - 'eurekaserver'

networks:
   spring-cloud-network:
      driver: 'bridge'
